version: '3'
services:
  gateway:
    image: suu_project_repository/gateway:latest
    ports:
      - 8080:8080
    environment:
      USER_SERVICE_IP: userservice
      MESSAGE_ROOM_SERVICE_IP: messageroomservice
      GATEWAY_IP: gateway
      JAEGER_HOST: jaeger

  userservice:
    image: suu_project_repository/userservice:latest
    environment:
      JAEGER_HOST: jaeger
    
  messageroomservice:
    image: suu_project_repository/messageroom:latest
    environment:
      MESSAGE_REGISTRY_SERVICE_IP: messageregistryservice
      USER_SERVICE_IP: userservice
      JAEGER_HOST: jaeger

  messageregistryservice:
    image: suu_project_repository/messageregistry:latest
    environment:
      JAEGER_HOST: jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.36.0
    hostname: jaeger
    ports:
      # - 5775:5775/udp
      # - 6831:6831/udp
      # - 6832:6832/udp
      # - 5778:5778
      - 16686:16686
      # - 9411:9411
      # - 55681:55681
